Repository ndleah/python-mini-project, pull requests merged in 2021-12, with the labels that each got.

#15 New Project Binary_tree
  Binary_tree/README.md
  Binary_tree/__pycache__/node.cpython-39.pyc
  Binary_tree/__pycache__/tree.cpython-39.pyc
  Binary_tree/main.py
  Binary_tree/node.py
  Binary_tree/tree.py
Labels: hacktoberfest-accepted

#17 Fixed an issue with the hangman program
  Hangman_Game/hangman.py
Labels: enhancement

#19 Add math_game
  Math_Game/README.md
  Math_Game/math_game.py
Labels: enhancement, hacktoberfest-accepted

#18 New project: Stack_structure
  Stack_structure/README.md
  Stack_structure/main.py
Labels: enhancement, hacktoberfest-accepted
