Repository ndleah/python-mini-project, pull requests merged in 2021-11, with the labels that each got.

#5 New Project: Speaking_Dictionary
  Speaking_Dictionary/README.md
  Speaking_Dictionary/Speaking_Dictionary.py
  Speaking_Dictionary/requirements.txt
Labels: enhancement, hacktoberfest-accepted

#6 New Project Cat_command
  Cat_command/README.md
  Cat_command/cat.py
  Cat_command/test_cat.txt
Labels: enhancement, hacktoberfest-accepted

#8 New Project Sqlite-crud
  IMG/sqlite-crud.png
  Sqlite-crud/README.md
  Sqlite-crud/database.db
  Sqlite-crud/main.py
Labels: hacktoberfest-accepted

#11 Hangman_Game: Fixed the text from You loose to You lose
  Hangman_Game/README.md
  Hangman_Game/hangman.py
Labels: bug
