Repository ndleah/python-mini-project, pull requests merged in 2022-01, with the labels that each got.

#26 Added WhatsappBot
  Whatsapp_Bot/README.md
  Whatsapp_Bot/main.py
Labels: bug, enhancement

#29 New project Crud_in_flask
  Crud_in_flask/README.Md
  Crud_in_flask/__pycache__/main.cpython-310.pyc
  Crud_in_flask/create_db.py
  Crud_in_flask/database.sql
  Crud_in_flask/main.py
  Crud_in_flask/static/styles/style.css
  Crud_in_flask/templates/base.html
  Crud_in_flask/templates/create.html
  Crud_in_flask/templates/edit.html
  Crud_in_flask/templates/index.html
  Youtube_video_download/main.py
Labels: enhancement, hacktoberfest-accepted

#31 Sudoku solver
  IMG/Sudoku_solver.jpg
  Sudoku_solver/README.md
  Sudoku_solver/main.py
Labels: enhancement, hacktoberfest-accepted

#32 New Project Addition
  IMG/vivekScreen01.png
  IMG/vivekScreen02.png
  QR Code Genrator/README.md
  QR Code Genrator/qrGenerator.py
  QR Code Genrator/requirements.txt
  README.md
Labels: enhancement, hacktoberfest-accepted

#36 Update README.md Whatsapp bot
  README.md
Labels: documentation, enhancement
